[project]
name = "whatsapp-mcp"
version = "0.1.0"
description = "WhatsApp MCP Server using Wati API"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.0",
    "python-dotenv>=0.21.0",
    "mcp>=1.6.0",
]

[project.optional-dependencies]
cli = ["mcp[cli]>=1.6.0"]
